/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.CargoDAO;
import dao.FuncionarioDAO;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import model.ObjCargo;
import model.ObjFuncionario;

/**
 *
 * @author 181710038
 */
public class FrmFuncionario1 extends javax.swing.JFrame {

    /**
     * Creates new form FrmFuncionario1
     */
    private TelaADM1 telaADM;
    private List<ObjCargo> listaDeCargos;
    
    public FrmFuncionario1() {
        initComponents();
        carregarCargos();
        
    }
    public FrmFuncionario1(TelaADM1 telaADM) {
        initComponents();
        this.telaADM = telaADM;
        carregarCargos();
        
    }
    
    public void carregarCargos (){
        listaDeCargos = CargoDAO.getCargos();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        ObjCargo cargo = new ObjCargo("Selecione...");
        listaDeCargos.add(0, cargo);
        
        for (ObjCargo car : listaDeCargos){
            modelo.addElement(car);
        }
        cbCargoFun.setModel(modelo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCPFFun = new javax.swing.JFormattedTextField();
        txtRGFun = new javax.swing.JTextField();
        txtTelefoneFun = new javax.swing.JTextField();
        cbEstadoCivilFun = new javax.swing.JComboBox<>();
        cbEscolaridadeFun = new javax.swing.JComboBox<>();
        txtEnderecoFun = new javax.swing.JTextField();
        txtNacionalidadeFun = new javax.swing.JTextField();
        cbCargoFun = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnSalvarFun = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnLimparFun = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNomeFun = new javax.swing.JTextField();
        cbSexoFun = new javax.swing.JComboBox<>();
        txtNascimentoFun = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionário");
        setResizable(false);

        try {
            txtCPFFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFFun.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        txtRGFun.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        txtTelefoneFun.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        cbEstadoCivilFun.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cbEstadoCivilFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Casado(a)", "Solteiro(a)", "Divorciado(a)", "Viúvo(a)" }));

        cbEscolaridadeFun.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cbEscolaridadeFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Fundamental Incompleto", "Fundamental Completo", "Médio Incompleto", "Médio Completo", "Superior Incompleto", "Superior Completo", "Pós Graduação" }));

        txtEnderecoFun.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        txtNacionalidadeFun.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        cbCargoFun.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setText("Nome:");

        btnSalvarFun.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnSalvarFun.setText("SALVAR");
        btnSalvarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFunActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setText("Sexo:");

        btnLimparFun.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnLimparFun.setText("LIMPAR");
        btnLimparFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFunActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel5.setText("Nascimento:");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel6.setText("CPF:");

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel7.setText("RG:");

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel8.setText("Telefone:");

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel9.setText("Estado Civil:");

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel10.setText("Escolaridade:");

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel11.setText("Endereço:");

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel12.setText("Nacionalidade:");

        jLabel13.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel13.setText("Cargo:");

        txtNomeFun.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        cbSexoFun.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cbSexoFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Maculino", "Feminino" }));

        try {
            txtNascimentoFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimentoFun.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtNascimentoFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNascimentoFunActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("T:\\Prints tech\\oft.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnSalvarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimparFun, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEscolaridadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefoneFun, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEstadoCivilFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRGFun, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCPFFun, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNascimentoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSexoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnderecoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNacionalidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(76, 76, 76)
                                .addComponent(cbCargoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(61, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSexoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNascimentoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPFFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRGFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefoneFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstadoCivilFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEscolaridadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNacionalidadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCargoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparFun, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFunActionPerformed
        
    
        
        ObjFuncionario funcionario = new ObjFuncionario();
        
        
        
        funcionario.setNome(txtNomeFun.getText());
        funcionario.setSexo(cbSexoFun.getSelectedIndex());
        String sData = txtNascimentoFun.getText();
        int dia = Integer.valueOf(  sData.substring(0, 2)   );
        int mes = Integer.valueOf(  sData.substring(3, 5)   );
        int ano = Integer.valueOf(  sData.substring(6, 10)   );
        Date data = new Date(ano, (mes - 1), dia);
        funcionario.setNascimento(data);
        funcionario.setCpf(txtCPFFun.getText());
        funcionario.setRg(txtRGFun.getText());
        funcionario.setTelefone(txtTelefoneFun.getText());
        funcionario.setEstado_civil(cbEstadoCivilFun.getSelectedItem().toString());
        funcionario.setEscolaridade(cbEscolaridadeFun.getSelectedItem().toString());
        funcionario.setEndereco(txtEnderecoFun.getText());
        funcionario.setNacionalidade(txtNacionalidadeFun.getText());
        funcionario.setCargo( (ObjCargo)  cbCargoFun.getSelectedItem() );
        
        FuncionarioDAO.inserir(funcionario);
        limpar();
        telaADM.carregarFuncionarios();
        
    }//GEN-LAST:event_btnSalvarFunActionPerformed

    private void btnLimparFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFunActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparFunActionPerformed

    private void txtNascimentoFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNascimentoFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNascimentoFunActionPerformed

    private void limpar (){
        txtNomeFun.setText("");
        cbSexoFun.setSelectedIndex(0);
        txtNascimentoFun.setText("");
        txtCPFFun.setText("");
        txtRGFun.setText("");
        txtTelefoneFun.setText("");
        cbEstadoCivilFun.setSelectedIndex(0);
        cbEscolaridadeFun.setSelectedIndex(0);
        txtEnderecoFun.setText("");
        txtNacionalidadeFun.setText("");
        cbCargoFun.setSelectedIndex(0);
        
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparFun;
    private javax.swing.JButton btnSalvarFun;
    private javax.swing.JComboBox<String> cbCargoFun;
    private javax.swing.JComboBox<String> cbEscolaridadeFun;
    private javax.swing.JComboBox<String> cbEstadoCivilFun;
    private javax.swing.JComboBox<String> cbSexoFun;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField txtCPFFun;
    private javax.swing.JTextField txtEnderecoFun;
    private javax.swing.JTextField txtNacionalidadeFun;
    private javax.swing.JFormattedTextField txtNascimentoFun;
    private javax.swing.JTextField txtNomeFun;
    private javax.swing.JTextField txtRGFun;
    private javax.swing.JTextField txtTelefoneFun;
    // End of variables declaration//GEN-END:variables
}
