/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.PacienteDAO;
import java.util.Date;
import model.ObjPaciente;

/**
 *
 * @author 181710038
 */
public class FrmPaciente1 extends javax.swing.JFrame {

    /**
     * Creates new form FrmPaciente1
     */
    private TelaSecretaria telaSecretaria;
    private boolean veioDaSecretaria;
    
    public FrmPaciente1() {
        initComponents();
        veioDaSecretaria = false;
      
    }
    
    public FrmPaciente1(TelaSecretaria telaSecretaria) {
        initComponents();
        this.telaSecretaria = telaSecretaria;
        veioDaSecretaria = true;
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTelefonePac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEnderecoPac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRGPac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbEstadoCivilPac = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        txtNomePac = new javax.swing.JTextField();
        cbSexoPac = new javax.swing.JComboBox<>();
        txtNascimentoPac = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        cbPlanoSaude = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Paciente");
        setResizable(false);

        txtTelefonePac.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtTelefonePac.setToolTipText("Cadastro de Paciente");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setText("Sexo:");
        jLabel4.setToolTipText("Cadastro de Paciente");

        txtEnderecoPac.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtEnderecoPac.setToolTipText("Cadastro de Paciente");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel5.setText("Nascimento:");
        jLabel5.setToolTipText("Cadastro de Paciente");

        txtRGPac.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtRGPac.setToolTipText("Cadastro de Paciente");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel6.setText("Telefone:");
        jLabel6.setToolTipText("Cadastro de Paciente");

        cbEstadoCivilPac.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cbEstadoCivilPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Casado(a)", "Solteiro(a)", "Divorciado(a)", "Viúvo(a)" }));
        cbEstadoCivilPac.setToolTipText("Cadastro de Paciente");

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel7.setText("Endereço:");
        jLabel7.setToolTipText("Cadastro de Paciente");

        jLabel14.setIcon(new javax.swing.ImageIcon("T:\\Prints tech\\oft.png")); // NOI18N
        jLabel14.setToolTipText("Cadastro de Paciente");

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel8.setText("RG:");
        jLabel8.setToolTipText("Cadastro de Paciente");

        btnSalvar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setToolTipText("Cadastro de Paciente");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel9.setText("Estado Civil:");
        jLabel9.setToolTipText("Cadastro de Paciente");

        btnLimpar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setToolTipText("Cadastro de Paciente");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        txtNomePac.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtNomePac.setToolTipText("Cadastro de Paciente");

        cbSexoPac.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cbSexoPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Masculino", "Feminino" }));
        cbSexoPac.setToolTipText("Cadastro de Paciente");

        try {
            txtNascimentoPac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimentoPac.setToolTipText("Cadastro de Paciente");
        txtNascimentoPac.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setText("Nome:");
        jLabel3.setToolTipText("Cadastro de Paciente");

        cbPlanoSaude.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cbPlanoSaude.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Unimed", "Sulmed", "Bradesco Saúde", "Doctor Clin", "Agemed", "Cassems" }));
        cbPlanoSaude.setToolTipText("Cadastro de Paciente");

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel10.setText("Plano de Saúde:");
        jLabel10.setToolTipText("Cadastro de Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEstadoCivilPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbPlanoSaude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEnderecoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRGPac, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonePac, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNascimentoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNomePac, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbSexoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbSexoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNascimentoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEnderecoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRGPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbEstadoCivilPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbPlanoSaude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ObjPaciente paciente = new ObjPaciente();
        paciente.setNome(txtNomePac.getText());
        paciente.setTelefone(txtTelefonePac.getText());
        paciente.setEndereco(txtEnderecoPac.getText());
        String sData = txtNascimentoPac.getText();
        int dia = Integer.valueOf(  sData.substring(0, 2)   );
        int mes = Integer.valueOf(  sData.substring(3, 5)   );
        int ano = Integer.valueOf(  sData.substring(6, 10)   );
        Date data = new Date(ano, (mes - 1), dia);
        paciente.setNascimento(data);
        paciente.setRg(txtRGPac.getText());
        paciente.setSexo( cbSexoPac.getSelectedIndex() );        
        paciente.setEstado_civil(cbEstadoCivilPac.getSelectedItem().toString());
        paciente.setPlano_saude(cbPlanoSaude.getSelectedItem().toString());
       
       
        PacienteDAO.inserir(paciente);
        Limpar();
        
        if(veioDaSecretaria)
            telaSecretaria.carregarPacientes();
        
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    public void Limpar(){
        txtNomePac.setText("");
        txtTelefonePac.setText("");
        txtEnderecoPac.setText("");
        txtNascimentoPac.setText("");
        txtRGPac.setText("");
        cbSexoPac.setSelectedIndex(0);
        cbEstadoCivilPac.setSelectedIndex(0);
        cbPlanoSaude.setSelectedIndex(0);
        
    }
    
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        Limpar();
        
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbEstadoCivilPac;
    private javax.swing.JComboBox<String> cbPlanoSaude;
    private javax.swing.JComboBox<String> cbSexoPac;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEnderecoPac;
    private javax.swing.JFormattedTextField txtNascimentoPac;
    private javax.swing.JTextField txtNomePac;
    private javax.swing.JTextField txtRGPac;
    private javax.swing.JTextField txtTelefonePac;
    // End of variables declaration//GEN-END:variables
}
