/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.ConsultaDAO;
import dao.LaudoDAO;
import model.ObjConsulta;
import model.ObjLaudo;

/**
 *
 * @author 181710038
 */
public class ListLaudo extends javax.swing.JFrame {

    private TelaMedico1 telaMedico;
    private ObjConsulta consulta;
    private boolean novo;
    
    /**
     * Creates new form ListConsultas
     */
    public ListLaudo() {
        initComponents();
        novo = true;
    }
    public ListLaudo(int codigo, TelaMedico1 telaMedico1 ){
        initComponents();
        consulta = ConsultaDAO.getConsultaByCodigo(codigo);
        
        txtNomePac.setText(consulta.getPaciente().getNome());
        String data = consulta.getData_consulta().getDate()+"/"+(consulta.getData_consulta().getMonth()+1)+"/"+consulta.getData_consulta().getYear();
        txtDataConsulta.setText(data);
        txtLaudo.setText(consulta.getLaudo());
        
        novo = false;
        this.telaMedico = telaMedico1;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPaciente = new javax.swing.JLabel();
        btnSalvarLaudo = new javax.swing.JButton();
        txtNomePac = new javax.swing.JLabel();
        lblPaciente1 = new javax.swing.JLabel();
        txtDataConsulta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLaudo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPaciente.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblPaciente.setText("Nome Paciente:");

        btnSalvarLaudo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnSalvarLaudo.setText("SALVAR");
        btnSalvarLaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLaudoActionPerformed(evt);
            }
        });

        txtNomePac.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtNomePac.setText("Nome");

        lblPaciente1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblPaciente1.setText("Data da Consulta:");

        txtDataConsulta.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtDataConsulta.setText("Data");

        txtLaudo.setColumns(20);
        txtLaudo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtLaudo.setRows(5);
        jScrollPane1.setViewportView(txtLaudo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPaciente1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataConsulta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomePac))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnSalvarLaudo)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomePac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataConsulta))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarLaudo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarLaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLaudoActionPerformed
        
        consulta.setLaudo(txtLaudo.getText());
        ConsultaDAO.editarLaudo(consulta);
        dispose();
        
    }//GEN-LAST:event_btnSalvarLaudoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarLaudo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblPaciente1;
    private javax.swing.JLabel txtDataConsulta;
    private javax.swing.JTextArea txtLaudo;
    private javax.swing.JLabel txtNomePac;
    // End of variables declaration//GEN-END:variables
}
