/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.FuncionarioDAO;
import dao.PacienteDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.ObjFuncionario;
import model.ObjPaciente;

/**
 *
 * @author 181710038
 */
public class TelaSecretaria extends javax.swing.JFrame {

    
    private List<ObjPaciente> listaDePacientes;
    private List<ObjFuncionario> listaDeMedicos;
    
    
    public TelaSecretaria() {
        initComponents();
        carregarPacientes();
        carregarMedicos();
        
    }
    
    public TelaSecretaria (int codigo, String nome){
        
    }
    
    public void carregarPacientes (){
        listaDePacientes = PacienteDAO.getPaciente();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        ObjPaciente paciente = new ObjPaciente("Selecione...");
        listaDePacientes.add(0, paciente);
        
        for( ObjPaciente pac : listaDePacientes){
            modelo.addElement( pac );
        }
        cbPacientes.setModel( modelo );
        
    }
    public void carregarMedicos (){
        
        listaDeMedicos = FuncionarioDAO.getMedicos();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        ObjFuncionario medico = new ObjFuncionario("Selecione...");
        listaDeMedicos.add(0, medico);
        
        for (ObjFuncionario med : listaDeMedicos){
            modelo.addElement(med);
        }
        cbMedicos.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMedicos = new javax.swing.JComboBox<>();
        btnListar = new javax.swing.JButton();
        btnCadastrarCon = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbPacientes = new javax.swing.JComboBox<>();
        btnCadastrarPac = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Secretaria");
        setResizable(false);

        cbMedicos.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cbMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedicosActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnListar.setText("Listar Consultas");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnCadastrarCon.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnCadastrarCon.setText("Cadastrar Consulta");
        btnCadastrarCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarConActionPerformed(evt);
            }
        });

        btnInfo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnInfo.setText("Informações");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("T:\\Prints tech\\oft.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Pacientes:");

        cbPacientes.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        cbPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPacientesActionPerformed(evt);
            }
        });

        btnCadastrarPac.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnCadastrarPac.setText("Cadastrar Paciente");
        btnCadastrarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPacActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("Lista de Médicos:");

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMedicos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrarCon, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbPacientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrarPac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarPac)
                    .addComponent(btnInfo))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarCon)
                    .addComponent(btnListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPacientesActionPerformed

    private void btnCadastrarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPacActionPerformed
        FrmPaciente1 pac = new FrmPaciente1(this);
        pac.setVisible(true);
    }//GEN-LAST:event_btnCadastrarPacActionPerformed

    private void btnCadastrarConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarConActionPerformed
        int posicao = cbMedicos.getSelectedIndex();
        if (posicao == 0 ){
            JOptionPane.showMessageDialog(this, "Selecione um médico!");
        }else{
          
           FrmConsulta1 con = new FrmConsulta1(this, (ObjFuncionario)cbMedicos.getSelectedItem());
           con.setVisible(true); 
        }
       
        
    }//GEN-LAST:event_btnCadastrarConActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
       int posicao = cbMedicos.getSelectedIndex();
        if (posicao == 0 ){
            JOptionPane.showMessageDialog(this, "Selecione um médico!");
        }else{
          
           ListaConsultasSec lis = new ListaConsultasSec(this, (ObjFuncionario)cbMedicos.getSelectedItem());
           lis.setVisible(true); 
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed

        int posicao = cbPacientes.getSelectedIndex();
        if (posicao == 0){
            JOptionPane.showMessageDialog(this, "Selecione um paciente!");
        }else{
            ObjPaciente pac = listaDePacientes.get(posicao);
            
            String sexo = "";
            if (pac.getSexo() == 1){
                sexo = "Masculino";
            }else{
                sexo = "Feminino";
            }
            
            String data = pac.getNascimento().getDate()+"/"+(pac.getNascimento().getMonth()+1)+"/"+pac.getNascimento().getYear();
            JOptionPane.showMessageDialog(this, "Nome: "+pac.getNome()+"\nSexo: "+sexo+"\nNascimento: "+data+"\nTelefone: "+pac.getTelefone()+"\nEndereço: "+pac.getEndereco()
           +"\nRG: "+pac.getRg()+"\nEstado Civil: "+pac.getEstado_civil()+"\nPlano de Saúde: "+pac.getPlano_saude());
        }
       
        
        
    }//GEN-LAST:event_btnInfoActionPerformed

    private void cbMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMedicosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        TelaInicial ini = new TelaInicial();
        ini.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

   

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCon;
    private javax.swing.JButton btnCadastrarPac;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> cbMedicos;
    private javax.swing.JComboBox<String> cbPacientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
